name: MultiLanguage
main: me.arno.multilanguage.MultiLanguage
version: 2.0.0
author: Anerach
description: >
            A multi-language support plugin for bukkit.
commands:
    multilanguage:
        description: Shows basic language information
        aliases: [lang, language, mlang, ml]
        usage: /<command>