name: MultiLanguage
main: me.plugin.multilanguage.MultiLanguage
version: 1.3.1
author: Anerach
dev-url: http://dev.bukkit.org/server-mods/multilanguage
description: >
            A multi-language support plugin for bukkit.
commands:
    multilanguage:
        description: Shows basic language information
        aliases: [lang, language, mlang, ml]
        usage: /<command>